name: Execute e2e
description: Setup and execute e2e tests

outputs:
  status:
    description: "e2e execution exit status"
    value: ${{ steps.e2e.outputs.status }}

runs:
  using: "composite"

  steps:
    - name: Install E2E Dependencies
      run: yarn install --prefer-offline
      shell: bash
      working-directory: e2e_tests

    - name: "Set up training-client Node"
      uses: ./.github/actions/setup-node

    - name: "Serve App"
      run: yarn env-cmd -f dev-resources/e2e.env react-scripts start &
      shell: bash

    - name: "Wait for App to be Served"
      run: npx wait-on http://localhost:3000
      shell: bash

    - name: Execute E2E
      id: e2e
      run: |
        export $(cat .env.ci | xargs) && npx playwright install && npx playwright test --workers=6
        exit_status=$?
        echo "status=$exit_status" >> "$GITHUB_OUTPUT"
      working-directory: e2e_tests
      shell: bash
