name: 'Deploy to app engine'
description: 'Builds and deploys the project to App Engine'

inputs:
  ENVIRONMENT:
    required: true
    type: string
  GCP_WORKLOAD_IDENTITY_PROVIDER:
    required: true
    type: string
  GCP_SERVICE_ACCOUNT:
    required: true
    type: string

runs:
  using: 'composite'

  steps:
    - name: "Authenticate to Google Cloud"
      id: gcp-auth
      uses: "google-github-actions/auth@v0.8.0"
      with:
        workload_identity_provider: "${{inputs.GCP_WORKLOAD_IDENTITY_PROVIDER}}"
        service_account: "${{inputs.GCP_SERVICE_ACCOUNT}}"
        token_format: "access_token"

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"

    - name: "Set up Node"
      uses: ./.github/actions/setup-node

    - name: "Build App"
      run: yarn build:${{inputs.ENVIRONMENT}}
      shell: bash

    - name: "Move build to deploy folder"
      run: cp -rf build deploy-resources
      shell: bash

    - name: "Deploy files to App Engine"
      uses: 'google-github-actions/deploy-appengine@v1'
      with:
        project_id: c1-training
        working_directory: ./deploy-resources
        deliverables: ./${{inputs.ENVIRONMENT}}.yaml
