name: 'Find and edit a comment'

inputs:
  COMMENT_TITLE:
    required: true
    type: string
  COMMENT_CONTENT:
    required: true
    type: string

runs:
  using: 'composite'

  steps:
    - name: Find Comment
      uses: peter-evans/find-comment@79dc7b44d7b20c1b39e90d366f91efb5f535de44
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: ${{ inputs.COMMENT_TITLE}}

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@521ce1b57b558684cf103470a4c687fbcd233228
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          **${{ inputs.COMMENT_TITLE}}**

          ${{ inputs.COMMENT_CONTENT }}

          Head: ${{ github.event.pull_request.head.sha }}

        edit-mode: replace
