name: Repo Level Constraints

on:
  pull_request:
    branches: [main]

jobs:
  check-commit-message-integrity:
    runs-on: ubuntu-latest
    steps:
      - name: Bad commit message blocker
        uses: platisd/bad-commit-message-blocker@009806d8ce1fe1e32138a8453bc1f6d73b746d83
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          remote_branch: main
