name: Deploy main to stage on merge (App Engine)

on:
  push:
    branches:
      - main
env:
  GCLOUD_PROJECT_ID: c1-training
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/315284125222/locations/global/workloadIdentityPools/github/providers/github-provider
  SERVICE_ACCOUNT: training-client-gha@c1-training.iam.gserviceaccount.com

permissions:
  contents: "read"
  id-token: "write"

jobs:
  deploy_to_stage:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Deploy to app engine instance"
        uses: ./.github/actions/deploy-to-app-engine
        with:
          GCP_WORKLOAD_IDENTITY_PROVIDER: ${{env.GCP_WORKLOAD_IDENTITY_PROVIDER}}
          GCP_SERVICE_ACCOUNT: ${{env.SERVICE_ACCOUNT}}
          ENVIRONMENT: stage
