name: Manually deploy to environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - stage
          - prod
      commit:
        description: "Commit to deploy"
        required: true
        type: string
        default: "main"

env:
  GCLOUD_PROJECT_ID: c1-training
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/315284125222/locations/global/workloadIdentityPools/github/providers/github-provider
  SERVICE_ACCOUNT: training-client-gha@c1-training.iam.gserviceaccount.com

permissions:
  contents: write
  id-token: write

jobs:
  deploy_to_environment:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit }}

      - name: 'Deploy to app engine instance'
        uses: ./.github/actions/deploy-to-app-engine
        with:
          GCP_WORKLOAD_IDENTITY_PROVIDER: ${{env.GCP_WORKLOAD_IDENTITY_PROVIDER}}
          GCP_SERVICE_ACCOUNT: ${{env.SERVICE_ACCOUNT}}
          ENVIRONMENT: ${{github.event.inputs.environment}}

      - name: 'Deploy to New Infra (Stage)'
        if: ${{ github.event.inputs.environment == 'stage' }}
        uses: ./.github/actions/use-gcp-integrations
        with:
          GCP_WORKLOAD_IDENTITY_PROVIDER: projects/419528211005/locations/global/workloadIdentityPools/my-pool/providers/github-training-client
          GCP_SERVICE_ACCOUNT: training-client-cicd@c1-fellow-non-prod.iam.gserviceaccount.com
          ENVIRONMENT: stage
          SHOULD_APPLY_INFRA: false
          DEPLOY_APPLICATION: true
          BUCKET_TO_DEPLOY: training-client-stage

      - name: 'Deploy to New Infra (Prod)'
        if: ${{ github.event.inputs.environment == 'prod' }}
        uses: ./.github/actions/use-gcp-integrations
        with:
          GCP_WORKLOAD_IDENTITY_PROVIDER: projects/287452642188/locations/global/workloadIdentityPools/infra-pool/providers/github-training-client
          GCP_SERVICE_ACCOUNT: training-client-cicd@c1-fellow-prod.iam.gserviceaccount.com
          ENVIRONMENT: prod
          SHOULD_APPLY_INFRA: false
          DEPLOY_APPLICATION: true
          BUCKET_TO_DEPLOY: training-client-prod

  tag_deployed_commit_with_date:
    if: ${{ github.event.inputs.environment == 'prod' }}
    runs-on: ubuntu-20.04
    needs: deploy_to_environment

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
              ref: ${{ github.event.inputs.commit }}

        - name: Get current time
          uses: josStorer/get-current-time@v2.0.2
          id: current-time
          with:
              format: YYYY.MM.DD-HH-mm
              utcOffset: '-05:00'

        - name: Set up github user name and email for tagging
          run: git config user.name ${{github.actor}} && git config user.email ${{github.actor}}@users.noreply.github.com

        - name: Tag commit manually
          run: git tag -a ${{steps.current-time.outputs.formattedTime}} ${{ github.event.inputs.commit }} -m "Commit deployed to prod on ${{steps.current-time.outputs.formattedTime}}"

        - name: Push created tag to the repo
          run: git push origin ${{steps.current-time.outputs.formattedTime}}
