name: Test

on:
  pull_request:
    branches: [main]

jobs:
  training-client-tests:
    name: "Check tests, linter and format"
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Node
        uses: ./.github/actions/setup-node

      - name: Check build
        run: yarn build

      - name: Run format check
        run: yarn format:check

      - name: Run lint check
        run: |
          yarn lint:js --max-warnings=0
          yarn lint:css --max-warnings=0

      - name: "Test and Report"
        uses: ./.github/actions/test-and-report
        with:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
